version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: clothing_store_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"  # Porta interna do container 5432 mapeada para a porta 5433 no host
    networks:
      - mynetwork

  node:
    image: node:latest
    container_name: clothing_node
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "dev"]
    ports:
     - "3003:3003"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@clothing_store_db:5432/${DB_NAME}
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
